# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dummy.proto',
  package='example.dummy',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x64ummy.proto\x12\rexample.dummy\"\x13\n\x05\x44ummy\x12\n\n\x02id\x18\x01 \x01(\rb\x06proto3')
)




_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='example.dummy.Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.dummy.Dummy.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), dict(
  DESCRIPTOR = _DUMMY,
  __module__ = 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:example.dummy.Dummy)
  ))
_sym_db.RegisterMessage(Dummy)


# @@protoc_insertion_point(module_scope)
