# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='map.proto',
  package='example.map',
  syntax='proto3',
  serialized_pb=_b('\n\tmap.proto\x12\x0b\x65xample.map\"\x17\n\tIdWrapper\x12\n\n\x02id\x18\x01 \x01(\r\"\x7f\n\nMapExample\x12-\n\x03ids\x18\x01 \x03(\x0b\x32 .example.map.MapExample.IdsEntry\x1a\x42\n\x08IdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.example.map.IdWrapper:\x02\x38\x01\x62\x06proto3')
)




_IDWRAPPER = _descriptor.Descriptor(
  name='IdWrapper',
  full_name='example.map.IdWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.map.IdWrapper.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=49,
)


_MAPEXAMPLE_IDSENTRY = _descriptor.Descriptor(
  name='IdsEntry',
  full_name='example.map.MapExample.IdsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='example.map.MapExample.IdsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='example.map.MapExample.IdsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=178,
)

_MAPEXAMPLE = _descriptor.Descriptor(
  name='MapExample',
  full_name='example.map.MapExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='example.map.MapExample.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MAPEXAMPLE_IDSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=178,
)

_MAPEXAMPLE_IDSENTRY.fields_by_name['value'].message_type = _IDWRAPPER
_MAPEXAMPLE_IDSENTRY.containing_type = _MAPEXAMPLE
_MAPEXAMPLE.fields_by_name['ids'].message_type = _MAPEXAMPLE_IDSENTRY
DESCRIPTOR.message_types_by_name['IdWrapper'] = _IDWRAPPER
DESCRIPTOR.message_types_by_name['MapExample'] = _MAPEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdWrapper = _reflection.GeneratedProtocolMessageType('IdWrapper', (_message.Message,), dict(
  DESCRIPTOR = _IDWRAPPER,
  __module__ = 'map_pb2'
  # @@protoc_insertion_point(class_scope:example.map.IdWrapper)
  ))
_sym_db.RegisterMessage(IdWrapper)

MapExample = _reflection.GeneratedProtocolMessageType('MapExample', (_message.Message,), dict(

  IdsEntry = _reflection.GeneratedProtocolMessageType('IdsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MAPEXAMPLE_IDSENTRY,
    __module__ = 'map_pb2'
    # @@protoc_insertion_point(class_scope:example.map.MapExample.IdsEntry)
    ))
  ,
  DESCRIPTOR = _MAPEXAMPLE,
  __module__ = 'map_pb2'
  # @@protoc_insertion_point(class_scope:example.map.MapExample)
  ))
_sym_db.RegisterMessage(MapExample)
_sym_db.RegisterMessage(MapExample.IdsEntry)


_MAPEXAMPLE_IDSENTRY.has_options = True
_MAPEXAMPLE_IDSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
