# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneof.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneof.proto',
  package='example.oneof',
  syntax='proto3',
  serialized_pb=_b('\n\x0boneof.proto\x12\rexample.oneof\"3\n\x06Result\x12\x11\n\x07message\x18\x01 \x01(\tH\x00\x12\x0c\n\x02id\x18\x02 \x01(\rH\x00\x42\x08\n\x06resultb\x06proto3')
)




_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='example.oneof.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.oneof.Result.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='example.oneof.Result.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='example.oneof.Result.result',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=81,
)

_RESULT.oneofs_by_name['result'].fields.append(
  _RESULT.fields_by_name['message'])
_RESULT.fields_by_name['message'].containing_oneof = _RESULT.oneofs_by_name['result']
_RESULT.oneofs_by_name['result'].fields.append(
  _RESULT.fields_by_name['id'])
_RESULT.fields_by_name['id'].containing_oneof = _RESULT.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'oneof_pb2'
  # @@protoc_insertion_point(class_scope:example.oneof.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
